# Site settings
url: http://vogelstpartystaging.github.io
title: Vogel Street Party
email: your-email@domain.com
author: Your Name
description: Vogel Street Party webste

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/vogelstparty
  - title: facebook
    url: https://facebook.com/vogelstreetparty

# Build settings
markdown: kramdown
permalink: pretty
