url: http://vogelstpartystaging.github.io
title: Vogel Street Party
email: your-email@domain.com
author: Your Name
description: Vogel Street Party webste

url: http://brianmaierjr.github.com/long-haul
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact
 - title: Sponsors
   url: /sponsors

social:
   twitter: vogelstparty
   facebook: vogelstreetparty
   email: vogelstreetparty@gmail.com

google_analytics: "UA-58263416-1"
